# Generated by Django 5.2.6 on 2026-07-28 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_payment'),
        ('users', '0003_remove_baseuser_address_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_shipping', to='users.shippingaddress', verbose_name='Shipping Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_billing', to='users.shippingaddress', verbose_name='Billing Address'),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
